global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cinevivid-backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/metrics'

  - job_name: 'cinevivid-frontend'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']